# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: kmom02-hand-in

on:
  pull_request:
    types:
      - opened

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'kmom02')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js lts
      uses: actions/setup-node@v4
      with:
        node-version: lts
        cache: 'npm'
    - run: npm run test-kmom02-hand-in
